config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root :to => 'site#index'

  get '/teams/join_team/:team_id', to: 'teams#join_team'

  resources :games

  resources :teams

  resources :user_profiles

  resources :events

  get '/join_game/:game_id/:team_id', to: 'games#join_game', as: :join_game

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :games

	# mount_uploader :image, ImageUploader
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :sport_type
	belongs_to :event
	has_many :teams, through: :game_associations
	has_many :game_associations

	def players
		players_array = []
		self.teams.each do |team|
			team.players.each do |player|
				players_array.push player
			end
		end
		return players_array
	end
end

app/models/game_association.rb
class GameAssociation < ActiveRecord::Base
	belongs_to :game
	belongs_to :team
end

app/models/sport_type.rb
class SportType < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :user_profiles
	has_many :games, through: :game_associations
	has_many :game_associations
	mount_uploader :image, ImageUploader
	def players
		return self.user_profiles
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :user_profile
	after_create :generate_profile

	def generate_profile
		new_user_profile = UserProfile.create(:user_id => self.id, :name => "CHANGE ME!")
	end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user
	belongs_to :team

	mount_uploader :image, ImageUploader

	validates_processing_of :image
	validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :generate_profile





  private

  def generate_profile

  	if current_user && !current_user.user_profile

  		new_user_profile = UserProfile.create(:user_id => current_user.id, :name => "CHANGE ME!")

  	end

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.order(created_at: :DESC)

	end

	def show
		
		@event = Event.find(params[:id])


	end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	
	def index

		@sport_types = SportType.order(created_at: :DESC)
	
	end

	def show

		@game = Game.find_by_id(params[:id])

		
	end

	def join_game
		team = Team.find_by_id(params[:team_id])
		game = Game.find_by_id(params[:game_id])
		new_game_assoc = GameAssociation.new()
		new_game_assoc.team_id = team.id
		new_game_assoc.game_id = game.id

		if new_game_assoc.save
			redirect_to "/events"
		else
			redirect_to event_path(game.event.id)
		end

	end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def index

		@events = Event.order(created_at: :ASC)[0..2]

	end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	before_action :authenticate_user!

	def index

		@teams = Team.order(created_at: :DESC)
	
	end

	def show

		@team = Team.find(params[:id])
			
		@upcoming_games = []
			@team.games.limit(6).each do |game|
				@upcoming_games.push(game)
			end

		@user_team = UserProfile.find_by_team_id(current_user.user_profile.team_id)

	end

	def edit

		@team = Team.find_by_id(params[:id])

	end
	def update
		team = Team.find_by_id(params[:id])
		if team.update(team_params)
			redirect_to teams_path
		else
			redirect_to edit_team_path(team.id)
		end
	end

	def new

		#will not allow user to create a new team, if already in one

		if current_user && current_user.user_profile && current_user.user_profile.team
			redirect_to(team_path current_user.user_profile.team.id)

		end

		@team = Team.new	

	end

	def create

		new_team = Team.new(team_params)

		if new_team.save

			current_user.user_profile.team_id=new_team.id

			current_user.user_profile.save

			redirect_to team_path(new_team.id)

		else
			redirect_to(new_team_path)
				# add error
		end

	end

	def join_team

		team = Team.find_by_id(params[:team_id])

		current_user.user_profile.team_id = team.id

		current_user.user_profile.save

		redirect_to team_path(team.id)

	end

	private

	def team_params

		params.require(:team).permit(:name, :image)
		
	end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController


	def show

		# @user_profile = UserProfile.find_by_id(current_user.user_profile.id)
		@user_profile = UserProfile.find_by_id(params[:id])


	end

	def edit

		@user_profile = UserProfile.find_by_id(current_user.user_profile.id)

	end

	def update
		target_user_profile = UserProfile.find_by_id(current_user.user_profile.id)
		if target_user_profile.update(user_profile_params)
			redirect_to user_profile_path(current_user.user_profile.id)
		else
			redirect_to(edit_user_profile_path current_user.user_profile.id)

		end
	end


	private 

		def user_profile_params

			params.require(:user_profile).permit(:name, :number, :description, :image)
		
		end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/events/index.html.erb
<body class="event_background">
<div class="title_box"><h1 class"center ">Upcoming Events:</h1></div>
<div class="jumbotron col-xs-12 col-sm-offset- col-sm-5">
	<ul class="list centered">

		
		<% @events.each do |event| %>
			 <% if event.date_time %>
                  <li><%= link_to event.name, event_path(event.id)  %> <%= event.date_time.strftime("%b")  %> <%= event.date_time.strftime("%d")  %> <%= event.date_time.strftime("%Y")  %></li><br>
              <% else %>
                   <li>No Time</li><br>
              <% end %>
		<% end %>


	</ul>
</div>
</body>

app/views/events/show.html.erb
<div class="jumbotron col-xs-12 col-sm-5">
	<div class="media-body">
    	<h1 class="media-heading"><%= @event.name   %></h1>
    	<h2><%= @event.date_time.strftime("%b")  %>, <%= @event.date_time.strftime("%Y")  %> - <%= @event.date_time.strftime("%l")  %>:<%= @event.date_time.strftime("%M")  %> <%= @event.date_time.strftime("%p")  %></h2>
    	<h4>Location: <%=@event.location  %></h4>  
	</div>
</div>

<div class="jumbotron col-xs-12 col-sm-offset-2 col-sm-5">
	<ul class="list-unstyled">
		<% @event.games.each do |game| %>

		<li><%= link_to game.name, game_path(game.id)  %></li>

		<% end %>
	</ul>
</div>

app/views/games/index.html.erb
<body class="game_background">
<div class="container">
<div class="box"><h1 class"center ">Available Games for Registration:</h1></div>

<% @sport_types.each do |type| %>
<div class="sport_type_section clearfix">
	<img src="<%= type.url %>" width='100%' height='100%' class="sport_type_image col-xs-12 col-md-4">
	<div class="sport_type_data col-xs-12 col-md-8">
		<h3 class="sport_type_heading"><%= type.name %></h3>
		<p class="sport_type_desc"><%= type.description %></p>		
	</div>
</div>
  <% end %>
</div>

</body>

app/views/games/show.html.erb
<div class="col-xs-col-12 jumbotron text-center">
	
	<h1><%= @game.name  %></h1>

	<%= link_to "Join this game", join_game_path(@game.id, current_user.user_profile.team_id)  %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Personalproject</title>
  <%= stylesheet_link_tag 'application', media: 'all'  %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>



<header>

<nav class="navbar navbar-default alert alert-info">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand courier">SportHub</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Games", games_path  %></li>
        <li><%= link_to "Events", events_path  %></li>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teams <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Current Teams/Join", teams_path  %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create Teams", new_team_path  %></li>

          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
          <ul class="dropdown-menu">
          
                  <% if current_user %>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
            <li role="separator" class="divider"></li>
                    <li><%= link_to "My Profile", user_profile_path(current_user.user_profile.id) %></li>
                  <% else %>
                    <li><%= link_to "Log In", new_user_session_path  %></li>
                  <% end %>


        </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>


</head>
<body>


   <div class="container">
<%= yield %>
  </div>
<footer>

</footer>
</body>

</html>

app/views/site/index.html.erb
<!DOCTYPE html>
<body class="background">
<div class="container">
  <div class="row">

    <div class="col-xs-8 center_box ">
    <h1 class="courier center_box_title">SportHub</h1>

   <p>SportHub is all about reliving the games we used to play as kids!  Through teams, you'll be able to set up matches with other teams in the area. Come around game day, both teams are notified and the game is set to play!</p>

   <p>Sed gravida, justo eget tincidunt porta, lorem est commodo est, non lobortis felis ligula sit amet diam. Mauris aliquam a eros viverra ultrices. Proin pellentesque quis mauris at pulvinar. Quisque maximus eleifend magna. Sed lacinia, libero et mollis accumsan, erat massa luctus elit, sed porta velit justo in magna. Phasellus commodo, orci posuere tristique finibus, enim nunc dictum risus, vitae viverra lacus lorem vestibulum massa. Quisque semper lacinia venenatis. Ut eget ornare odio. Curabitur eu mauris non lectus rhoncus hendrerit. Vivamus sit amet posuere massa. Sed eget mattis sem. Nunc placerat, ligula sit amet efficitur semper, urna risus tincidunt felis, ut feugiat dolor ipsum eget risus.</p>

   <p>Vestibulum vitae metus id dui tincidunt malesuada. Nulla facilisi. Aenean eget scelerisque enim, ac dignissim lorem. Nulla finibus sapien congue blandit euismod. In vel metus suscipit, vulputate tortor eget, aliquet sapien. Pellentesque dignissim tempor massa a aliquet. Cras eros augue, faucibus vel risus sit amet, porta efficitur nunc. Integer pellentesque ultrices nunc, a iaculis augue. Etiam id iaculis elit. Donec ullamcorper ultrices nibh non sollicitudin.</p>

   <p>Nunc pharetra libero lectus, vitae tincidunt elit fermentum ut. Integer sagittis, justo id varius laoreet, mauris mauris aliquam nibh, vel hendrerit enim mi non est. Donec finibus, diam non fermentum ullamcorper, enim velit vestibulum ante, pellentesque ullamcorper nibh elit quis dolor. Phasellus tempor lorem in egestas suscipit. Proin eget varius diam, eu tristique nunc. Mauris ut augue vitae orci blandit convallis. Aenean vel lectus pulvinar, placerat nulla sit amet, aliquam dui. Fusce sed imperdiet nulla. Morbi malesuada nibh eget ipsum rhoncus congue.</p>






    </div>
          <div class="col-xs-1">
          </div>




          <div class="col-xs-3 center_box">
         <h3>Upcoming Events:</h3>
           <%  @events.each do |event| %>
              <div class="panel panel-default">
               <div class="panel-heading">
               <% if event.date_time %>
                  <h3 class="panel-title"><%= event.date_time.strftime("%b")  %> <%= event.date_time.strftime("%d")  %> <%= event.date_time.strftime("%Y")  %></h3>
              <% else %>
                   <h3 class="panel-title">No time></h3>
              <% end %>
                </div>
                <div class="panel-body">
                  <%= event.name %>
                </div>
              </div>
            <% end %>
          </div>
  </div>

</div>
</body>
</html>

app/views/user_profiles/edit.html.erb
<%= form_for @user_profile, html: { multipart: true } do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>
 
      <ul>
      <% @user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul> 
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>


  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/show.html.erb
<div class="jumbotron center col-xs-12">

  <div class="row">
    <div class="col-xs-12 col-md-3">  
      <% if @user_profile.image? %>
        <%= image_tag @user_profile.image.thumb, class: 'img-responsive center-block img-rounded' %>
      <% else %>
        <img src="https://www.eyeem.com/node-static/img/profile-placeholder.jpg">
      <% end %>
    </div>
    <div class="col-xs-12 col-md-9">

      <% if current_user.user_profile.id  === @user_profile.id %>

          <div class="media-body">
          <h1 class="media-heading"> Welcome <%= @user_profile.name   %> ! </h1>
          <h2>Phone Number on recond: <%= @user_profile.number  %></h2>
          <h2>Current Team: <%= @user_profile.team.name  %></h2>
          <h5>About me: <%= @user_profile.description  %></h5>
          <p><%= link_to "Edit Profile", edit_user_profile_path(@user_profile.id)  %></p>

          </div>

      <% else %>

        <div class="media-body">
          <h1 class="media-heading"><%= @user_profile.name   %>'s Profile</h1>
          <h2>Phone Number on recond: <%= @user_profile.number  %></h2>
          <h5>About <%=@user_profile.name  %>: <%= @user_profile.description  %></h5> 
           !!!  
        </div>
      <% end %>
    </div>
  </div>
</div>